// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Client from "react-dom/client";
import * as NewImplementation from "./NewImplementation.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as NewImplementationPpx from "./NewImplementationPpx.res.mjs";
import * as NewImplementationTheme from "./NewImplementationTheme.res.mjs";
import Typography from "@mui/material/Typography";
import * as NewImplementationThemePpx from "./NewImplementationThemePpx.res.mjs";

function Index$App(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx(NewImplementation.make, {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx(NewImplementationTheme.make, {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx("center", {
        children: JsxRuntime.jsx(Typography, {
          variant: "h4",
          children: "PPX Result"
        })
      }),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx(NewImplementationPpx.make, {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx("br", {}),
      JsxRuntime.jsx(NewImplementationThemePpx.make, {})
    ]
  });
}

let App = {
  make: Index$App
};

let el = Stdlib_Option.getOrThrow(Primitive_option.fromNullable(document.querySelector("#app")), undefined);

Client.createRoot(el).render(JsxRuntime.jsx(Index$App, {}));

export {
  App,
  el,
}
/* el Not a pure module */
