// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@mui/styles";
import * as JsxRuntime from "react/jsx-runtime";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";

let useStyles = Styles.makeStyles({
  rounded: {
    backgroundColor: "grey",
    color: "white",
    padding: "15px"
  },
  root: {
    margin: "0 auto",
    maxWidth: "970px",
    width: "100%"
  }
}, {
  classNamePrefix: "xxx"
});

let Styles$1 = {
  useStyles: useStyles
};

function NewImplementationPpx(props) {
  let classes = useStyles();
  return JsxRuntime.jsx(Paper, {
    children: JsxRuntime.jsx(Typography, {
      children: "Some Content"
    }),
    classes: {
      root: classes.root,
      rounded: classes.rounded
    }
  });
}

let make = NewImplementationPpx;

export {
  Styles$1 as Styles,
  make,
}
/* useStyles Not a pure module */
