// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import Paper from "@mui/material/Paper";
import * as Styles from "@material-ui/core/styles";
import Typography from "@mui/material/Typography";

let useStyles = Styles.makeStyles(theme => ({
  root: {
    margin: "0 auto",
    maxWidth: "970px",
    width: "100%"
  },
  rounded: {
    backgroundColor: theme.palette.background.paper,
    color: theme.palette.text.primary,
    padding: "15px"
  }
}));

let Styles$1 = {
  useStyles: useStyles
};

function NewImplementationTheme(props) {
  let classes = useStyles();
  return JsxRuntime.jsx(Paper, {
    children: JsxRuntime.jsx(Typography, {
      children: "Some Content"
    }),
    classes: {
      root: classes.root,
      rounded: classes.rounded
    }
  });
}

let make = NewImplementationTheme;

export {
  Styles$1 as Styles,
  make,
}
/* useStyles Not a pure module */
