// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/core/styles";

function options_generateId() {
  return "blasdnsad" + String(Js_math.random_int(0, 100));
}

var options = {
  classNamePrefix: "xxx",
  generateId: options_generateId
};

var useStyles = Styles.makeStyles({
      rounded: {
        backgroundColor: "grey",
        color: "white",
        padding: "15px"
      },
      root: {
        margin: "0 auto",
        maxWidth: "970px",
        width: "100%"
      }
    }, options);

var Styles$1 = {
  useStyles: useStyles
};

function NewImplementationPpx(props) {
  var classes = useStyles();
  return JsxRuntime.jsx(Core.Paper, {
              children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                        children: "Some Content"
                      })),
              classes: {
                root: classes.root,
                rounded: classes.rounded
              }
            });
}

var make = NewImplementationPpx;

export {
  Styles$1 as Styles,
  make ,
}
/* useStyles Not a pure module */
