// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@mui/styles";
import * as JsxRuntime from "react/jsx-runtime";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";

let useStyles = Styles.makeStyles(_theme => ({
  rounded: {},
  root: {}
}), {
  name: "test"
});

let Styles1 = {
  useStyles: useStyles
};

let useStyles$1 = Styles.makeStyles(theme => ({
  rounded: {
    backgroundColor: theme.palette.background.paper,
    color: theme.palette.text.primary,
    padding: "15px"
  },
  root: {
    margin: "0 auto",
    maxWidth: "970px",
    width: "100%"
  }
}));

let Styles2 = {
  useStyles: useStyles$1
};

let useStyles$2 = Styles.makeStyles({
  rounded: {
    backgroundColor: "#eee",
    color: "#333",
    padding: "15px"
  },
  root: {
    margin: "0 auto",
    maxWidth: "970px",
    width: "100%"
  }
});

let Styles3 = {
  useStyles: useStyles$2
};

let useStyles$3 = Styles.makeStyles({
  rounded: {
    backgroundColor: "#eee",
    color: "#333",
    padding: "15px"
  },
  root: {
    margin: "0 auto",
    maxWidth: "970px",
    width: "100%"
  }
}, {
  name: "test"
});

let Styles4 = {
  useStyles: useStyles$3
};

function NewImplementationThemePpx(props) {
  useStyles();
  useStyles$1();
  useStyles$2();
  useStyles$3();
  return JsxRuntime.jsx(Paper, {
    children: JsxRuntime.jsx(Typography, {
      children: "Some Content"
    })
  });
}

let make = NewImplementationThemePpx;

export {
  Styles1,
  Styles2,
  Styles3,
  Styles4,
  make,
}
/* useStyles Not a pure module */
