// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@mui/styles";

let useStyles = Styles.makeStyles(_theme => ({
  root: {}
}), {
  name: "test"
});

let Styles$1 = {
  useStyles: useStyles
};

export {
  Styles$1 as Styles,
}
/* useStyles Not a pure module */
