// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "mui/styles";

var useStyles = Styles.makeStyles({
      root: {},
      rounded: {}
    });

var classes = useStyles();

export {
  useStyles ,
  classes ,
}
/* useStyles Not a pure module */
