// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "mui/styles";

let useStyles = Styles.makeStyles({
  root: {},
  rounded: {}
});

let classes = useStyles();

export {
  useStyles,
  classes,
}
/* useStyles Not a pure module */
