name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-14]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: 'moonrepo/setup-proto@v0'
      - run: proto use

      - name: Use OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.1

      - run: opam install . --deps-only
        working-directory: public/rescript-material-ui-ppx

      - run: opam exec -- dune build
        working-directory: public/rescript-material-ui-ppx

      - name: Yarn install
        run: yarn install --immutable

      - name: Build PPX test project
        working-directory: ppx-test
        run: yarn build

      # - name: Upload artifacts ${{ matrix.os }}
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.os }}
      #     path: public/rescript-material-ui-ppx/_build/default/src/bin.exe
      #   env:
      #     CI: true

  publish:
    if: github.event_name != 'pull_request'
    needs: build
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download linux artifacts
        uses: actions/download-artifact@master
        with:
          name: ubuntu-22.04
          path: public/rescript-material-ui-ppx/binaries/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@master
        with:
          name: macOS-14
          path: public/rescript-material-ui-ppx/binaries/darwin

      # - name: Download windows artifacts
      #   uses: actions/download-artifact@master
      #   with:
      #     name: windows-latest
      #     path: public/rescript-material-ui-ppx/binaries/windows

      - name: Move artifacts
        run: |
          mkdir -p public/rescript-material-ui-ppx/bin
          mv public/rescript-material-ui-ppx/binaries/darwin/bin.exe public/rescript-material-ui-ppx/bin/rescript_material_ui_ppx-darwin-x64.exe
          # mv public/rescript-material-ui-ppx/binaries/windows/bin.exe public/rescript-material-ui-ppx/bin/rescript_material_ui_ppx-win-x64.exe
          mv public/rescript-material-ui-ppx/binaries/linux/bin.exe public/rescript-material-ui-ppx/bin/rescript_material_ui_ppx-linux-x64.exe
          rm -rf public/rescript-material-ui-ppx/binaries

      - uses: 'moonrepo/setup-proto@v0'
      - run: proto use

      - name: Publish
        working-directory: public/rescript-material-ui-ppx
        run: yarn publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
