name: CI

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-14]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Use OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.1

      - run: opam install . --deps-only
        working-directory: public/rescript-material-ui-ppx

      - run: opam exec -- dune build --verbose; ls -l _build/install/default/bin
        working-directory: public/rescript-material-ui-ppx

      - name: Yarn install
        run: yarn install --immutable

      - name: Build PPX test project
        working-directory: ppx-test
        run: yarn build

      - name: Upload artifacts ${{ matrix.os }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: public/rescript-material-ui-ppx/_build/default/src/Bin.exe
        env:
          CI: true

  publish:
    if: github.event_name != 'pull_request'
    needs: build
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download linux artifacts (x64)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-22.04-x64
          path: ppx/binaries/linux-x64

      - name: Download linux artifacts (arm64)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-22.04-arm64
          path: ppx/binaries/linux-arm64

      - name: Download macOS artifacts (x64)
        uses: actions/download-artifact@v4
        with:
          name: macOS-14-x64
          path: ppx/binaries/darwin-x64

      - name: Download macOS artifacts (arm64)
        uses: actions/download-artifact@v4
        with:
          name: macOS-14-arm64
          path: ppx/binaries/darwin-arm64

      - name: Move artifacts
        working-directory: public/rescript-material-ui-ppx
        run: |
          mkdir bin
          mv binaries/darwin-x64/Bin.exe bin/rescript_material_ui_ppx-darwin-x64.exe
          mv binaries/darwin-arm64/Bin.exe bin/rescript_material_ui_ppx-darwin-arm64.exe
          mv binaries/linux-x64/Bin.exe bin/rescript_material_ui_ppx-linux-x64.exe
          mv binaries/linux-arm64/Bin.exe bin/rescript_material_ui_ppx-linux-arm64.exe
          rm -rf binaries

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: yarn pack
        working-directory: public/rescript-material-ui-ppx
        run: yarn pack --dry-run
      # - name: Publish
      #   working-directory: public/rescript-material-ui-ppx
      #   run: yarn publish --access public
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
